# Generated by Django 5.0.4 on 2024-04-09 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.CharField(editable=False, primary_key=True, serialize=False)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('card_number', models.CharField(max_length=16, unique=True)),
                ('token', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
