# Generated by Django 5.0.4 on 2024-04-09 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Card',
        ),
    ]
