# Generated by Django 5.0.4 on 2024-04-09 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_card_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='user',
        ),
    ]
