# Generated by Django 5.0.4 on 2024-05-10 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_category_payment_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='payment_id',
            field=models.CharField(default=123, max_length=100, unique=True),
            preserve_default=False,
        ),
    ]
