# Generated by Django 5.0.4 on 2024-04-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_card_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='id',
            field=models.CharField(editable=False, primary_key=True, serialize=False),
        ),
    ]
