# Generated by Django 5.0.3 on 2024-05-10 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_category_payment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='card_id',
            field=models.CharField(max_length=100),
        ),
    ]
