# Generated by Django 5.0.3 on 2024-05-16 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_category_card_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='currency',
            field=models.CharField(default=145, max_length=10),
            preserve_default=False,
        ),
    ]
