# Generated by Django 5.0.4 on 2024-04-09 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('authentication', '0003_initial'),
        ('main', '0003_remove_card_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='cards',
            field=models.ManyToManyField(blank=True, to='main.card'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='groups',
            field=models.ManyToManyField(to='auth.group'),
        ),
    ]
