# Generated by Django 5.0.4 on 2024-04-10 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_alter_customuser_cards_alter_customuser_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cards',
        ),
    ]
